/**
 * @file
 * @item name in korean
**/

#include "item-prop-enum.h"
#include "potion-type.h"
#include "book-type.h"


const map<int, string> weapon_kor = 
{
    {WPN_CLUB,                  "몽둥이"},
    {WPN_WHIP,                  "채찍"},
    {WPN_MACE,                  "메이스"},
    {WPN_FLAIL,                 "플레일"},
    {WPN_MORNINGSTAR,           "모닝스타"},
    {WPN_DIRE_FLAIL,            "다이어 플레일"},
    {WPN_EVENINGSTAR,           "이브닝스타"},
    {WPN_GREAT_MACE,            "대형 메이스"},

    {WPN_DAGGER,                "단도"},
    {WPN_QUICK_BLADE,           "퀵 블레이드"},
    {WPN_SHORT_SWORD,           "단검"},
    {WPN_RAPIER,                "레이피어"},

    {WPN_FALCHION,              "펄션"},
    {WPN_LONG_SWORD,            "장검"},
    {WPN_SCIMITAR,              "시미터"},
    {WPN_GREAT_SWORD,           "대검"},

    {WPN_HAND_AXE,              "손도끼"},
    {WPN_WAR_AXE,               "워 액스"},
    {WPN_BROAD_AXE,             "브로드 액스"},
    {WPN_BATTLEAXE,             "배틀 액스"},
    {WPN_EXECUTIONERS_AXE,      "처형자의 도끼"},

    {WPN_SPEAR,                 "창"},
    {WPN_TRIDENT,               "삼지창"},
    {WPN_HALBERD,               "할버드"},
    {WPN_GLAIVE,                "글레이브"},
    {WPN_BARDICHE,              "바디셰"},

    {WPN_BLOWGUN,               "바람총"},

    {WPN_HAND_CROSSBOW,         "손 쇠뇌"},
    {WPN_ARBALEST,              "아발레스트"},
    {WPN_TRIPLE_CROSSBOW,       "삼중석궁"},


    {WPN_SHORTBOW,              "단궁"},
    {WPN_LONGBOW,               "장궁"},

    {WPN_HUNTING_SLING,         "사냥용 투석구"},
    {WPN_FUSTIBALUS,            "푸스티발루스"},

    {WPN_DEMON_WHIP,            "악마의 채찍"},
    {WPN_GIANT_CLUB,            "거대 몽둥이"},
    {WPN_GIANT_SPIKED_CLUB,     "가시박힌 거대 몽둥이"},

    {WPN_DEMON_BLADE,           "악마의 칼"},
    {WPN_DOUBLE_SWORD,          "이중검"},
    {WPN_TRIPLE_SWORD,          "삼중검"},

    {WPN_DEMON_TRIDENT,         "악마의 삼지창"},
    {WPN_SCYTHE,                "낫"},

    {WPN_STAFF,                 "지팡이"},
    {WPN_QUARTERSTAFF,          "육척봉"},
    {WPN_LAJATANG,              "라자탕"},

    {WPN_EUDEMON_BLADE,         "성령의 검"},
    {WPN_SACRED_SCOURGE,        "성스러운 천벌"},
    {WPN_TRISHULA,              "트리슐라"},
};


const map<int, string> missile_kor = 
{
    {MI_NEEDLE,                 "바늘"},
    {MI_ARROW,                  "화살"},
    {MI_BOLT,                   "볼트"},
    {MI_JAVELIN,                "자벨린"},
    {MI_STONE,                  "돌"},
    {MI_LARGE_ROCK,             "바위"},
    {MI_SLING_BULLET,           "투석구"},
    {MI_THROWING_NET,           "투척용 그물"},
    {MI_TOMAHAWK,               "토마호크"},
};


const map<int, string> armour_kor = 
{
    {ARM_ROBE,                  "로브"},
    {ARM_LEATHER_ARMOUR,        "가죽 갑옷"},
    {ARM_RING_MAIL,             "고리 갑옷"},
    {ARM_SCALE_MAIL,            "미늘 갑옷"},
    {ARM_CHAIN_MAIL,            "사슬 갑옷"},
    {ARM_PLATE_ARMOUR,          "판금 갑옷"},
    {ARM_CRYSTAL_PLATE_ARMOUR,  "수정 판금 갑옷"},
    {ARM_CLOAK,                 "망토"},
    {ARM_SCARF,                 "스카프"},
    {ARM_HAT,                   "모자"},
    {ARM_HELMET,                "투구"},
    {ARM_GLOVES,                "장갑"},
    {ARM_BOOTS,                 "신발"},

    {ARM_BUCKLER,               "버클러"},
    {ARM_SHIELD,                "방패"},
    {ARM_LARGE_SHIELD,          "대형 방패"},

    {ARM_ANIMAL_SKIN,           "동물 가죽"},
    {ARM_TROLL_LEATHER_ARMOUR,  "트롤 가죽 갑옷"},

    {ARM_FIRE_DRAGON_ARMOUR,    "화염 용 비늘"},
    {ARM_ICE_DRAGON_ARMOUR,     "얼음 용 비늘"},
    {ARM_STEAM_DRAGON_ARMOUR,   "증기 용 비늘"},
    {ARM_ACID_DRAGON_ARMOUR,    "산성 용 비늘"},
    {ARM_STORM_DRAGON_ARMOUR,   "천둥 용 비늘"},
    {ARM_GOLD_DRAGON_ARMOUR,    "황금 용 비늘"},
    {ARM_SWAMP_DRAGON_ARMOUR,   "늪지 용 비늘"},
    {ARM_PEARL_DRAGON_ARMOUR,   "진주 용 비늘"},
    {ARM_SHADOW_DRAGON_ARMOUR,  "그림자 용 비늘"},
    {ARM_QUICKSILVER_DRAGON_ARMOUR, "수은 용 비늘"},

    {ARM_CENTAUR_BARDING,       "센타우르 마갑"},
    {ARM_NAGA_BARDING,          "나가 꼬리갑옷"},
};

const map<int, string> wand_kor = 
{
    {WAND_FLAME,                "불꽃"},
    {WAND_PARALYSIS,            "마비"},
//    {WAND_CONFUSION,            "혼란"},
    {WAND_DIGGING,              "굴착"},
    {WAND_ICEBLAST,             "얼음 폭발"},
//    {WAND_LIGHTNING,            "번개"},
    {WAND_POLYMORPH,            "변이"},
    {WAND_ENSLAVEMENT,          "노예화"},
    {WAND_ACID,                 "산성"},
    {WAND_RANDOM_EFFECTS,       "무작위 효과"},
    {WAND_DISINTEGRATION,       "분해"},
    {WAND_CLOUDS,               "구름"},
    {WAND_SCATTERSHOT,          "산탄"},
};

// might be useless
const map<int, string> food_kor =
{
//    {FOOD_MEAT_RATION,          "고기 식량"},
    {FOOD_BREAD_RATION,         "빵 식량"},
    {FOOD_ROYAL_JELLY,          "로얄 젤리"},
    {FOOD_FRUIT,                "과일"},
    {FOOD_CHUNK,                "고깃덩이"},
};


const map<int, string> scroll_kor =
{
    {SCR_IDENTIFY,              "식별"},
    {SCR_TELEPORTATION,         "공간이동"},
    {SCR_FEAR,                  "공포"},
    {SCR_NOISE,                 "소음"},
    {SCR_REMOVE_CURSE,          "저주 해제"},
    {SCR_SUMMONING,             "소환"},
    {SCR_ENCHANT_WEAPON,        "무기 강화"},
    {SCR_ENCHANT_ARMOUR,        "방어구 강화"},
    {SCR_TORMENT,               "고문"},
    {SCR_RANDOM_USELESSNESS,    "쓸모없는 무작위"},
    {SCR_IMMOLATION,            "발화"},
    {SCR_BLINKING,              "순간이동"},
    {SCR_MAGIC_MAPPING,         "마법적 탐색"},
    {SCR_FOG,                   "안개"},
    {SCR_ACQUIREMENT,           "획득"},
    {SCR_BRAND_WEAPON,          "무기 속성 부여"},
    {SCR_RECHARGING,            "충전"},
    {SCR_HOLY_WORD,             "신성한 언어"},
    {SCR_VULNERABILITY,         "취약"},
    {SCR_SILENCE,               "침묵"},
    {SCR_AMNESIA,               "망각"},
};

const map<int, string> jewellery_kor =
{
    {RING_PROTECTION,           "보호"},
    {RING_PROTECTION_FROM_FIRE, "화염 저항"},
    {RING_POISON_RESISTANCE,    "독 저항"},
    {RING_PROTECTION_FROM_COLD, "냉기 저항"},
    {RING_STRENGTH,             "힘"},
    {RING_SLAYING,              "살육"},
    {RING_SEE_INVISIBLE,        "투명 보기"},
    {RING_RESIST_CORROSION,     "산성 저항"},
//    {RING_LOUDNESS,             "소음"},
    {RING_TELEPORTATION,        "공간이동"},
    {RING_EVASION,              "회피"},
    {RING_STEALTH,              "은신"},
    {RING_DEXTERITY,            "민첩"},
    {RING_INTELLIGENCE,         "지능"},
    {RING_WIZARDRY,             "마법사"},
    {RING_MAGICAL_POWER,        "마력"},
    {RING_FLIGHT,               "비행"},
    {RING_LIFE_PROTECTION,      "양 에너지"},
    {RING_PROTECTION_FROM_MAGIC, "마법 저항"},
    {RING_FIRE,                 "화염"},
    {RING_ICE,                  "얼음"},

    {AMU_RAGE,                  "격노"},
    {AMU_HARM,                  "아픔"},
    {AMU_MANA_REGENERATION,     "마법 재생"},
    {AMU_THE_GOURMAND,          "대식가"},
    {AMU_INACCURACY,            "부정확"},
    {AMU_NOTHING,               "공백"},
    {AMU_GUARDIAN_SPIRIT,       "수호령"},
    {AMU_FAITH,                 "신앙"},
    {AMU_REFLECTION,            "반사"},
    {AMU_REGENERATION,          "재생"},
};


const map<int, string> potion_kor =
{
    {POT_CURING,                "치료"},
    {POT_HEAL_WOUNDS,           "상처 치유"},
    {POT_HASTE,                 "가속"},
    {POT_MIGHT,                 "힘"},
    {POT_BRILLIANCE,            "총명함"},
    {POT_AGILITY,               "날쌤"},
    {POT_FLIGHT,                "비행"},
    {POT_CANCELLATION,          "취소"},
    {POT_AMBROSIA,              "암브로시아"},
    {POT_INVISIBILITY,          "투명"},
    {POT_DEGENERATION,          "약화"},
    {POT_EXPERIENCE,            "경험"},
    {POT_MAGIC,                 "마력"},
    {POT_BERSERK_RAGE,          "광폭화"},
    {POT_MUTATION,              "변이"},
    {POT_RESISTANCE,            "저항"},
    {POT_BLOOD,                 "피"},
    {POT_LIGNIFY,               "수목화"},
};

const map<int, string> book_kor =
{
    {BOOK_MINOR_MAGIC,          "하급 마법"},
    {BOOK_CONJURATIONS,         "파괴술"},
    {BOOK_FLAMES,               "불꽃"},
    {BOOK_FROST,                "서리"},
    {BOOK_SUMMONINGS,           "소환술"},
    {BOOK_FIRE,                 "화염"},
    {BOOK_ICE,                  "얼음"},
    {BOOK_SPATIAL_TRANSLOCATIONS, "공간 전이"},
    {BOOK_ENCHANTMENTS,         "주술"},
    {BOOK_YOUNG_POISONERS,      "초보 독술사 입문서"},
    {BOOK_TEMPESTS,             "폭풍"},
    {BOOK_DEATH,                "죽음"},
    {BOOK_MISFORTUNE,           "불운"},
    {BOOK_CHANGES,              "변화"},
    {BOOK_TRANSFIGURATIONS,     "변신"},
    {BOOK_FEN,                  "펜 폴리오"},
    {BOOK_BATTLE,               "전투"},
    {BOOK_CLOUDS,               "구름"},
    {BOOK_NECROMANCY,           "강령술"},
    {BOOK_CALLINGS,             "부름"},
    {BOOK_MALEDICT,             "저주"},
    {BOOK_AIR,                  "대기"},
    {BOOK_SKY,                  "하늘"},
    {BOOK_WARP,                 "왜곡"},
    {BOOK_UNLIFE,               "불생"},
    {BOOK_GEOMANCY,             "흙점술"},
    {BOOK_EARTH,                "대지"},
    {BOOK_POWER,                "힘"},
    {BOOK_CANTRIPS,             "장난"},
    {BOOK_PARTY_TRICKS,         "파티용 마술"},
    {BOOK_DEBILITATION,         "약화"},
    {BOOK_DRAGON,               "용"},
    {BOOK_BURGLARY,             "도둑질"},
    {BOOK_DREAMS,               "꿈"},
    {BOOK_ALCHEMY,              "연금술"},
    {BOOK_BEASTS,               "짐승"},
    {BOOK_ANNIHILATIONS,        "섬멸"},
    {BOOK_GRAND_GRIMOIRE,       "대 마도서"},
    {BOOK_NECRONOMICON,         "네크로노미콘"},
    {BOOK_MANUAL,               "설명서"}
};

const map<int, string> staff_kor =
{
    {STAFF_WIZARDRY,            "마법사"},
    {STAFF_POWER,               "힘"},
    {STAFF_FIRE,                "화염"},
    {STAFF_COLD,                "냉기"},
    {STAFF_POISON,              "독"},
    {STAFF_ENERGY,              "에너지"},
    {STAFF_DEATH,               "죽음"},
    {STAFF_CONJURATION,         "파괴"},
    {STAFF_SUMMONING,           "소환"},
    {STAFF_AIR,                 "대기"},
    {STAFF_EARTH,               "대지"},
};

const map<int, string> miscellany_kor = 
{
    {MISC_FAN_OF_GALES,         "질풍의 부채"},
    {MISC_LAMP_OF_FIRE,         "화염의 램프"},
    {MISC_HORN_OF_GERYON,       "게리욘의 뿔"},
    {MISC_BOX_OF_BEASTS,        "짐승상자"},
    {MISC_CRYSTAL_BALL_OF_ENERGY, "에너지 수정구"},
    {MISC_LIGHTNING_ROD,        "번개 마법막대"},

    {MISC_DECK_OF_ESCAPE,       "탈출"},
    {MISC_DECK_OF_DESTRUCTION,  "파괴"},
    {MISC_DECK_OF_SUMMONING,    "소환"},
    {MISC_DECK_OF_PUNISHMENT,   "징벌"},

    {MISC_QUAD_DAMAGE,          "대미지 4배"},

    {MISC_PHIAL_OF_FLOODS,      "홍수의 물병"},
    {MISC_SACK_OF_SPIDERS,      "거미 주머니"},
    {MISC_ZIGGURAT,             "지구라트 모형"},

    {MISC_PHANTOM_MIRROR,       "환영 거울"},
};

const map<int, string> rune_kor =
{
    {RUNE_SWAMP,                "부패"},
    {RUNE_SNAKE,                "뱀무늬"}, // serpentine은 사문석 인듯
    {RUNE_SHOALS,               "따개비"},
    {RUNE_SLIME,                "끈적끈적한"},
    {RUNE_ELF,                  "엘프"},
    {RUNE_VAULTS,               "은"},
    {RUNE_TOMB,                 "황금"},
    {RUNE_DIS,                  "강철"},
    {RUNE_GEHENNA,              "흑요석"},
    {RUNE_COCYTUS,              "차가운"},
    {RUNE_TARTARUS,             "뼈"},
    {RUNE_ABYSSAL,              "심연"},
    {RUNE_DEMONIC,              "악마"},
    {RUNE_MNOLEG,               "빛나는"},
    {RUNE_LOM_LOBON,            "마법의"},
    {RUNE_CEREBOV,              "이글거리는"},
    {RUNE_GLOORX_VLOQ,          "어둠의"},
    {RUNE_SPIDER,               "거미줄"},
    {RUNE_FOREST,               "숲"},
};

const map<int, string> monster_kor = 
{
    {MONS_PROGRAM_BUG, "프로그램 버그"},
    {MONS_WORKER_ANT, "일꾼 개미"},
    {MONS_QUEEN_ANT, "여왕 개미"},
    {MONS_SOLDIER_ANT, "병정 개미"},
    {MONS_FORMICID, "포미시드"},
    {MONS_ENTROPY_WEAVER, "엔트로피 방직꾼"},
    {MONS_BAT, "박쥐"},
    {MONS_BUTTERFLY, "나비"},
    {MONS_VAMPIRE_BAT, "흡혈 박쥐"},
    {MONS_FIRE_BAT, "불박쥐"},
    {MONS_BENNU, "벤누"},
    {MONS_CAUSTIC_SHRIKE, "부식성 까치"},
    {MONS_SHARD_SHRIKE, "파편 까치"},
    {MONS_CENTAUR, "켄타우로스"},
    {MONS_CENTAUR_WARRIOR, "켄타우로스 전사"},
    {MONS_YAKTAUR, "야크타우로스"},
    {MONS_YAKTAUR_CAPTAIN, "야크타우로스 대장"},
    {MONS_FAUN, "파우누스"},
    {MONS_SATYR, "사티로스"},
    {MONS_DRACONIAN, "드라코니언"},
    {MONS_BLACK_DRACONIAN, "검은 드라코니언"},
    {MONS_YELLOW_DRACONIAN, "노란 드라코니언"},
    {MONS_PALE_DRACONIAN, "창백한 드라코니언"},
    {MONS_GREEN_DRACONIAN, "녹색 드라코니언"},
    {MONS_PURPLE_DRACONIAN, "보라 드라코니언"},
    {MONS_RED_DRACONIAN, "붉은 드라코니언"},
    {MONS_WHITE_DRACONIAN, "흰 드라코니언"},
    {MONS_GREY_DRACONIAN, "회색 드라코니언"},
    {MONS_DRACONIAN_STORMCALLER, "드라코니언 폭풍소환사"},
    {MONS_DRACONIAN_MONK, "드라코니언 수도승"},
    {MONS_DRACONIAN_SHIFTER, "드라코니언 전이술사"},
    {MONS_DRACONIAN_ANNIHILATOR, "드라코니언 섬멸자"},
    {MONS_DRACONIAN_KNIGHT, "드라코니언 기사"},
    {MONS_DRACONIAN_SCORCHER, "드라코니언 화염술사"},
    {MONS_ELF, "엘프"},
    {MONS_DEEP_ELF_KNIGHT, "딥 엘프 기사"},
    {MONS_DEEP_ELF_ARCHER, "딥 엘프 궁수"},
    {MONS_DEEP_ELF_BLADEMASTER, "딥 엘프 검귀"},
    {MONS_DEEP_ELF_MASTER_ARCHER, "딥 엘프 활의 대가"},
    {MONS_DEEP_ELF_MAGE, "딥 엘프 마법사"},
    {MONS_DEEP_ELF_HIGH_PRIEST, "딥 엘프 고위 사제"},
    {MONS_DEEP_ELF_DEMONOLOGIST, "딥 엘프 악마술사"},
    {MONS_DEEP_ELF_ANNIHILATOR, "딥 엘프 섬멸자"},
    {MONS_DEEP_ELF_SORCERER, "딥 엘프 마도사"},
    {MONS_DEEP_ELF_DEATH_MAGE, "딥 엘프 강령술사"},
    {MONS_DEEP_ELF_ELEMENTALIST, "딥 엘프 원소술사"},
    {MONS_WANDERING_MUSHROOM, "방황하는 버섯"},
    {MONS_DEATHCAP, "죽음의 갓버섯"},
    {MONS_THORN_HUNTER, "가시 사냥꾼"},
    {MONS_SHAMBLING_MANGROVE, "꾸물거리는 맹그로브"},
    {MONS_VINE_STALKER, "바인 스토커"},
    {MONS_GOBLIN, "고블린"},
    {MONS_HOBGOBLIN, "홉고블린"},
    {MONS_GNOLL, "놀"},
    {MONS_GNOLL_SHAMAN, "놀 주술사"},
    {MONS_GNOLL_SERGEANT, "놀 분대장"},
    {MONS_BOGGART, "보가트"},
    {MONS_DWARF, "드워프"},
    {MONS_DEEP_DWARF, "딥 드워프"},
    {MONS_JACKAL, "자칼"},
    {MONS_HOUND, "사냥개"},
    {MONS_HOWLER_MONKEY, "고함 원숭이"},
    {MONS_WARG, "와르그"},
    {MONS_WOLF, "늑대"},
    {MONS_HOG, "돼지"},
    {MONS_HELL_HOUND, "지옥 사냥개"},
    {MONS_DOOM_HOUND, "파멸 사냥개"},
    {MONS_RAIJU, "뇌수"},
    {MONS_HELL_HOG, "지옥의 돼지"},
    {MONS_HOLY_SWINE, "성스러운 돼지"},
    {MONS_FELID, "펠리드"},
    {MONS_POLAR_BEAR, "북극곰"},
    {MONS_BLACK_BEAR, "흑곰"},
    {MONS_SPRIGGAN, "스프리건"},
    {MONS_SPRIGGAN_RIDER, "스프리건 기수"},
    {MONS_SPRIGGAN_DRUID, "스프리건 드루이드"},
    {MONS_SPRIGGAN_BERSERKER, "스프리건 광전사"},
    {MONS_SPRIGGAN_AIR_MAGE, "스프리건 대기술사"},
    {MONS_SPRIGGAN_DEFENDER, "스프리건 수호자"},
    {MONS_SWAMP_DRAKE, "늪지 드레이크"},
    {MONS_RIME_DRAKE, "서리 드레이크"},
    {MONS_WIND_DRAKE, "바람 드레이크"},
    {MONS_LINDWURM, "린드웜"},
    {MONS_DEATH_DRAKE, "죽음의 드레이크"},
    {MONS_FRILLED_LIZARD, "목도리 도마뱀"},
    {MONS_LEOPARD_GECKO, "표범 도마뱀붙이"},
    {MONS_IGUANA, "이구아나"},
    {MONS_BASILISK, "바실리스크"},
    {MONS_WYVERN, "와이번"},
    {MONS_KOMODO_DRAGON, "코모도왕도마뱀"},
    {MONS_MERFOLK, "머포크"},
    {MONS_MERFOLK_IMPALER, "머포크 창술사"},
    {MONS_MERFOLK_JAVELINEER, "머포크 투창병"},
    {MONS_MERFOLK_AQUAMANCER, "머포크 파도술사"},
    {MONS_MERFOLK_SIREN, "머포크 사이렌"},
    {MONS_MERFOLK_AVATAR, "머포크 인도자"},
    {MONS_WATER_NYMPH, "물의 요정"},
    {MONS_BOG_BODY, "늪지 시체"},
    {MONS_NECROPHAGE, "시체 포식자"},
    {MONS_GHOUL, "구울"},
    {MONS_ORC, "오크"},
    {MONS_ORC_WIZARD, "오크 마법사"},
    {MONS_ORC_PRIEST, "오크 사제"},
    {MONS_ORC_WARRIOR, "오크 전사"},
    {MONS_ORC_KNIGHT, "오크 기사"},
    {MONS_ORC_WARLORD, "오크 전쟁군주"},
    {MONS_ORC_SORCERER, "오크 마도사"},
    {MONS_ORC_HIGH_PRIEST, "오크 고위 사제"},
    {MONS_LAVA_ORC, "용암 오크"},
    {MONS_HUMAN, "인간"},
    {MONS_SLAVE, "노예"},
    {MONS_HELL_KNIGHT, "지옥의 기사"},
    {MONS_DEATH_KNIGHT, "죽음의 기사"},
    {MONS_NECROMANCER, "강령술사"},
    {MONS_WIZARD, "마법사"},
    {MONS_VAULT_GUARD, "보물창고 수호병"},
    {MONS_VAULT_SENTINEL, "보물창고 보초병"},
    {MONS_VAULT_WARDEN, "보물창고 간수장"},
    {MONS_IRONBRAND_CONVOKER, "강철인장 소환사"},
    {MONS_IMPERIAL_MYRMIDON, "제국 미르미돈"},
    {MONS_SERVANT_OF_WHISPERS, "속삭임의 하수인"},
    {MONS_RAGGED_HIEROPHANT, "남루한 사제장"},
    {MONS_IRONHEART_PRESERVER, "강철심장 수호자"},
    {MONS_SHAPESHIFTER, "변신수"},
    {MONS_GLOWING_SHAPESHIFTER, "빛나는 변신수"},
    {MONS_KILLER_KLOWN, "살인 광대"},
    {MONS_DEMIGOD, "반신"},
    {MONS_HALFLING, "하플링"},
    {MONS_RAT, "쥐"},
    {MONS_QUOKKA, "쿼카"},
    {MONS_RIVER_RAT, "강가 쥐"},
    {MONS_HELL_RAT, "지옥 쥐"},
    {MONS_PORCUPINE, "고슴도치"},
    {MONS_GIANT_COCKROACH, "거대 바퀴벌레"},
    {MONS_SCORPION, "전갈"},
    {MONS_EMPEROR_SCORPION, "황제 전갈"},
    {MONS_DEATH_SCARAB, "죽음의 풍뎅이"},
    {MONS_TARANTELLA, "타란튤라"},
    {MONS_JUMPING_SPIDER, "깡총 거미"},
    {MONS_WOLF_SPIDER, "늑대거미"},
    {MONS_REDBACK, "붉은등거미"},
    {MONS_DEMONIC_CRAWLER, "악마의 벌레"},
    {MONS_ORB_SPIDER, "구체 거미"},
    {MONS_CROCODILE, "크로커다일"},
    {MONS_ALLIGATOR, "엘리게이터"},
    {MONS_SNAPPING_TURTLE, "늑대거북"},
    {MONS_ALLIGATOR_SNAPPING_TURTLE, "악어거북"},
    {MONS_FIRE_CRAB, "화염 게"},
    {MONS_GHOST_CRAB, "유령 게"},
    {MONS_APOCALYPSE_CRAB, "묵시의 게"},
    {MONS_UGLY_THING, "흉측한 것"},
    {MONS_VERY_UGLY_THING, "매우 흉측한 것"},
    {MONS_FIRE_VORTEX, "화염 소용돌이"},
    {MONS_SPATIAL_VORTEX, "공간의 소용돌이"},
    {MONS_SPATIAL_MAELSTROM, "큰 공간의 소용돌이"},
    {MONS_INSUBSTANTIAL_WISP, "실체가 없는 위습"},
    {MONS_TWISTER, "회오리"},
    {MONS_WORM, "지렁이"},
    {MONS_SWAMP_WORM, "늪지렁이"},
    {MONS_TYRANT_LEECH, "폭군 거머리"},
    {MONS_DART_SLUG, "다트 민달팽이"},
    {MONS_TORPOR_SNAIL, "무기력함의 달팽이"},
    {MONS_ELEPHANT_SLUG, "코끼리 민달팽이"},
    {MONS_UNSEEN_HORROR, "보이지 않는 공포"},
    {MONS_ABOMINATION_SMALL, "작은 흉물"},
    {MONS_CRAWLING_CORPSE, "기어다니는 시체"},
    {MONS_MACABRE_MASS, "끔찍한 덩어리"},
    {MONS_ANCIENT_ZYME, "고대의 병원균"},
    {MONS_WORLDBINDER, "차원연결체"},
    {MONS_KILLER_BEE, "킬러 비"},
    {MONS_QUEEN_BEE, "여왕벌"},
    {MONS_VAMPIRE_MOSQUITO, "흡혈 모기"},
    {MONS_HORNET, "말벌"},
    {MONS_MELIAI, "멜리아이"},
    {MONS_SPARK_WASP, "전격 말벌"},
    {MONS_GHOST_MOTH, "유령 나방"},
    {MONS_MOTH_OF_WRATH, "격노의 나방"},
    {MONS_WIGHT, "망자"},
    {MONS_SKELETAL_WARRIOR, "해골 전사"},
    {MONS_ANCIENT_CHAMPION, "고대의 영웅"},
    {MONS_FLYING_SKULL, "날아다니는 해골"},
    {MONS_CURSE_SKULL, "저주의 해골"},
    {MONS_CURSE_TOE, "저주의 발가락"},
    {MONS_ANGEL, "천사"},
    {MONS_CHERUB, "케루빔"},
    {MONS_SERAPH, "세라프"},
    {MONS_PROFANE_SERVITOR, "타천사"},
    {MONS_CYCLOPS, "키클롭스"},
    {MONS_FIRE_GIANT, "화염 거인"},
    {MONS_FROST_GIANT, "서리 거인"},
    {MONS_JUGGERNAUT, "저거너트"},
    {MONS_IRON_GIANT, "강철 거인"},
    {MONS_FIRE_DRAGON, "화염 용"},
    {MONS_HYDRA, "히드라"},
    {MONS_ICE_DRAGON, "얼음 용"},
    {MONS_STEAM_DRAGON, "증기 용"},
    {MONS_SWAMP_DRAGON, "늪지 용"},
    {MONS_ACID_DRAGON, "산성 용"},
    {MONS_QUICKSILVER_DRAGON, "수은 용"},
    {MONS_IRON_DRAGON, "강철 용"},
    {MONS_STORM_DRAGON, "폭풍 용"},
    {MONS_GOLDEN_DRAGON, "황금 용"},
    {MONS_SHADOW_DRAGON, "그림자 용"},
    {MONS_BONE_DRAGON, "뼈다귀 용"},
    {MONS_PEARL_DRAGON, "진주 용"},
    {MONS_EARTH_ELEMENTAL, "대지 정령"},
    {MONS_FIRE_ELEMENTAL, "불 정령"},
    {MONS_WATER_ELEMENTAL, "물 정령"},
    {MONS_AIR_ELEMENTAL, "대기 정령"},
    {MONS_IRON_ELEMENTAL, "강철 정령"},
    {MONS_ELEMENTAL_WELLSPRING, "정령의 우물샘"},
    {MONS_BULLFROG, "황소 개구리"},
    {MONS_SPINY_FROG, "가시 개구리"},
    {MONS_BLINK_FROG, "깜빡이 개구리"},
    {MONS_BARACHI, "바라키"},
    {MONS_FLOATING_EYE, "떠다니는 눈알"},
    {MONS_EYE_OF_DRAINING, "흡수의 눈알"},
    {MONS_GLOWING_ORANGE_BRAIN, "빛나는 주황색 뇌"},
    {MONS_GREAT_ORB_OF_EYES, "거대한 눈알의 구체"},
    {MONS_SHINING_EYE, "빛나는 눈알"},
    {MONS_EYE_OF_DEVASTATION, "황폐의 눈알"},
    {MONS_GOLDEN_EYE, "황금 눈알"},
    {MONS_OPHAN, "오펀"},
    {MONS_HIPPOGRIFF, "히포그리프"},
    {MONS_MANTICORE, "맨티코어"},
    {MONS_MINOTAUR, "미노타우르스"},
    {MONS_SPHINX, "스핑크스"},
    {MONS_HARPY, "하피"},
    {MONS_MUTANT_BEAST, "돌연변이 짐승"},
    {MONS_ANCESTOR, "선조"},
    {MONS_ANCESTOR_KNIGHT, "기사"},
    {MONS_ANCESTOR_BATTLEMAGE, "전투 마법사"},
    {MONS_ANCESTOR_HEXER, "주술사"},
    {MONS_OOZE, "진흙괴물"},
    {MONS_JELLY, "젤리"},
    {MONS_SLIME_CREATURE, "슬라임 덩어리"},
    {MONS_AZURE_JELLY, "하늘빛 젤리"},
    {MONS_DEATH_OOZE, "죽음의 점액"},
    {MONS_ACID_BLOB, "산성 방울"},
    {MONS_KOBOLD, "코볼드"},
    {MONS_BIG_KOBOLD, "큰 코볼드"},
    {MONS_KOBOLD_DEMONOLOGIST, "코볼드 악마학자"},
    {MONS_LICH, "리치"},
    {MONS_ANCIENT_LICH, "고대 리치"},
    {MONS_REVENANT, "사령"},
    {MONS_HALAZID_WARLOCK, "할라지드 흑마도사"},
    {MONS_MUMMY, "미라"},
    {MONS_GUARDIAN_MUMMY, "미라 수호병"},
    {MONS_GREATER_MUMMY, "위대한 미라"},
    {MONS_MUMMY_PRIEST, "미라 사제"},
    {MONS_NAGA, "나가"},
    {MONS_NAGA_MAGE, "나가 마법사"},
    {MONS_NAGA_SHARPSHOOTER, "나가 명사수"},
    {MONS_NAGA_RITUALIST, "나가 의식술사"},
    {MONS_NAGA_WARRIOR, "나가 전사"},
    {MONS_NAGARAJA, "나가라쟈"},
    {MONS_OGRE, "오우거"},
    {MONS_TWO_HEADED_OGRE, "쌍두 오우거"},
    {MONS_OGRE_MAGE, "오우거 마법사"},
    {MONS_PLANT, "잡초"},
    {MONS_DEMONIC_PLANT, "악령 들린 잡초"},
    {MONS_WITHERED_PLANT, "말라 비틀어진 잡초"},
    {MONS_OKLOB_SAPLING, "오클롭 묘목"},
    {MONS_OKLOB_PLANT, "오클롭 식물"},
    {MONS_BUSH, "덤불"},
    {MONS_BURNING_BUSH, "불타는 덤불"},
    {MONS_TOADSTOOL, "독버섯"},
    {MONS_FUNGUS, "곰팡이"},
    {MONS_BALLISTOMYCETE, "폭발성 진균류"},
    {MONS_HYPERACTIVE_BALLISTOMYCETE, "활성화된 폭발성 진균류"},
    {MONS_BRIAR_PATCH, "가시덤불"},
    {MONS_TENGU, "텐구"},
    {MONS_TENGU_CONJURER, "텐구 요술사"},
    {MONS_TENGU_WARRIOR, "텐구 전사"},
    {MONS_TENGU_REAVER, "텐구 약탈자"},
    {MONS_EFREET, "이프리트"},
    {MONS_RAKSHASA, "락샤사"},
    {MONS_DRYAD, "드라이어드"},
    {MONS_SNAPLASHER_VINE, "철썩 덩굴"},
    {MONS_SNAPLASHER_VINE_SEGMENT, "철썩 덩굴의 일부"},
    {MONS_BALL_PYTHON, "비단뱀"},
    {MONS_ADDER, "살무사"},
    {MONS_WATER_MOCCASIN, "물뱀"},
    {MONS_BLACK_MAMBA, "블랙 맘바"},
    {MONS_SEA_SNAKE, "바다뱀"},
    {MONS_ANACONDA, "아나콘다"},
    {MONS_GUARDIAN_SERPENT, "수호자 구렁이"},
    {MONS_SHOCK_SERPENT, "전격 구렁이"},
    {MONS_MANA_VIPER, "마나 독사"},
    {MONS_TROLL, "트롤"},
    {MONS_IRON_TROLL, "강철 트롤"},
    {MONS_DEEP_TROLL, "딥 트롤"},
    {MONS_DEEP_TROLL_EARTH_MAGE, "딥 트롤 대지술사"},
    {MONS_DEEP_TROLL_SHAMAN, "딥 트롤 주술사"},
    {MONS_VAMPIRE, "뱀파이어"},
    {MONS_VAMPIRE_KNIGHT, "뱀파이어 기사"},
    {MONS_VAMPIRE_MAGE, "뱀파이어 마법사"},
    {MONS_JIANGSHI, "강시"},
    {MONS_GHOST, "유령"},
    {MONS_PHANTOM, "환영"},
    {MONS_HUNGRY_GHOST, "굶주린 유령"},
    {MONS_FLAYED_GHOST, "갈기갈기 찢긴 유령"},
    {MONS_PLAYER_GHOST, "플레이어 유령"},
    {MONS_SHADOW, "그림자"},
    {MONS_SILENT_SPECTRE, "정적의 악령"},
    {MONS_DROWNED_SOUL, "익사한 영혼"},
    {MONS_WRAITH, "망령"},
    {MONS_SHADOW_WRAITH, "그림자 망령"},
    {MONS_FREEZING_WRAITH, "냉기 망령"},
    {MONS_EIDOLON, "에이돌론"},
    {MONS_PHANTASMAL_WARRIOR, "환영 전사"},
    {MONS_ABOMINATION_LARGE, "커다란 흉물"},
    {MONS_THRASHING_HORROR, "몸부림치는 공포"},
    {MONS_TENTACLED_MONSTROSITY, "촉수괴물"},
    {MONS_ORB_GUARDIAN, "오브 수호자"},
    {MONS_TENTACLED_STARSPAWN, "촉수투성이 별"},
    {MONS_STARSPAWN_TENTACLE, "별의 촉수"},
    {MONS_STARSPAWN_TENTACLE_SEGMENT, "별의 촉수 일부"},
    {MONS_STARCURSED_MASS, "저주받은 별덩어리"},
    {MONS_DREAM_SHEEP, "꿈 양"},
    {MONS_YAK, "야크"},
    {MONS_DEATH_YAK, "죽음의 야크"},
    {MONS_ELEPHANT, "코끼리"},
    {MONS_DIRE_ELEPHANT, "난폭한 코끼리"},
    {MONS_HELLEPHANT, "지옥 코끼리"},
    {MONS_APIS, "아피스"},
    {MONS_ICE_BEAST, "얼음 짐승"},
    {MONS_SKY_BEAST, "하늘 짐승"},
    {MONS_ZOMBIE, "좀비"},
    {MONS_SKELETON, "해골"},
    {MONS_SIMULACRUM, "얼음형상"},
    {MONS_ZOMBIE_SMALL, "작은 좀비"},
    {MONS_SKELETON_SMALL, "작은 해골"},
    {MONS_SIMULACRUM_SMALL, "작은 얼음형상"},
    {MONS_ZOMBIE_LARGE, "커다란 좀비"},
    {MONS_SKELETON_LARGE, "커다란 해골"},
    {MONS_SIMULACRUM_LARGE, "커다란 얼음형상"},
    {MONS_SPECTRAL_THING, "영체"},
    {MONS_ELECTRIC_EEL, "전기뱀장어"},
    {MONS_KRAKEN, "크라켄"},
    {MONS_KRAKEN_TENTACLE, "촉수"},
    {MONS_KRAKEN_TENTACLE_SEGMENT, "촉수 일부"},
    {MONS_OCTOPODE, "옥토포드"},
    {MONS_LAVA_SNAKE, "용암 뱀"},
    {MONS_SALAMANDER, "샐러맨더"},
    {MONS_SALAMANDER_MYSTIC, "샐러맨더 신비술사"},
    {MONS_HELLBINDER, "지옥연결자"},
    {MONS_CLOUD_MAGE, "구름마법사"},
    {MONS_PLAYER_ILLUSION, "플레이어 환영"},
    {MONS_PLAYER_SHADOW, "그림자"},
    {MONS_DANCING_WEAPON, "춤추는 무기"},
    {MONS_SPECTRAL_WEAPON, "영체 무기"},
    {MONS_ELDRITCH_TENTACLE, "으스스한 촉수"},
    {MONS_ELDRITCH_TENTACLE_SEGMENT, "으스스한 촉수 일부"},
    {MONS_DEMONSPAWN, "데몬스폰"},
    {MONS_MONSTROUS_DEMONSPAWN, "흉악한 데몬스폰"},
    {MONS_GELID_DEMONSPAWN, "싸늘한 데몬스폰"},
    {MONS_INFERNAL_DEMONSPAWN, "지옥불 데몬스폰"},
    {MONS_TORTUROUS_DEMONSPAWN, "일그러진 데몬스폰"},
    {MONS_BLOOD_SAINT, "피의 성자"},
    {MONS_WARMONGER, "전쟁광"},
    {MONS_CORRUPTER, "타락자"},
    {MONS_BLACK_SUN, "검은 태양"},
    {MONS_CRIMSON_IMP, "핏빛 임프"},
    {MONS_QUASIT, "콰짓"},
    {MONS_WHITE_IMP, "하얀 임프"},
    {MONS_UFETUBUS, "우페터버스"},
    {MONS_IRON_IMP, "강철 임프"},
    {MONS_SHADOW_IMP, "그림자 임프"},
    {MONS_RUST_DEVIL, "녹투성이 악마"},
    {MONS_ORANGE_DEMON, "오렌지색 악마"},
    {MONS_RED_DEVIL, "붉은 악마"},
    {MONS_HELLWING, "헬윙"},
    {MONS_ICE_DEVIL, "얼음의 악마"},
    {MONS_CHAOS_SPAWN, "혼돈의 찌꺼기"},
    {MONS_SUN_DEMON, "태양의 악마"},
    {MONS_SOUL_EATER, "영혼포식자"},
    {MONS_SMOKE_DEMON, "연기의 악마"},
    {MONS_NEQOXEC, "네퀘젝"},
    {MONS_YNOXINUL, "녹시눌"},
    {MONS_SIXFIRHY, "식스파이리"},
    {MONS_SHADOW_DEMON, "그림자 악마"},
    {MONS_GREEN_DEATH, "녹색 죽음"},
    {MONS_BLIZZARD_DEMON, "눈보라 악마"},
    {MONS_BALRUG, "발록"},
    {MONS_CACODEMON, "캐커데몬"},
    {MONS_HELL_BEAST, "지옥의 짐승"},
    {MONS_HELLION, "헬리온"},
    {MONS_REAPER, "사신"},
    {MONS_LOROCYPROCA, "로코키프로카"},
    {MONS_TORMENTOR, "고통의 악마"},
    {MONS_BRIMSTONE_FIEND, "유황불 핀드"},
    {MONS_ICE_FIEND, "아이스 핀드"},
    {MONS_TZITZIMITL, "치치미틀"},
    {MONS_HELL_SENTINEL, "지옥의 감시자"},
    {MONS_EXECUTIONER, "처형자"},
    {MONS_SALTLING, "소금 덩어리"},
    {MONS_PEACEKEEPER, "평화유지자"},
    {MONS_IRON_GOLEM, "강철 골렘"},
    {MONS_CRYSTAL_GUARDIAN, "수정 수호자"},
    {MONS_TOENAIL_GOLEM, "발톱 골렘"},
    {MONS_ELECTRIC_GOLEM, "전기 골렘"},
    {MONS_USHABTI, "우샤바티"},
    {MONS_GUARDIAN_GOLEM, "수호자 골렘"},
    {MONS_SPELLFORGED_SERVITOR, "주문연성 하인"},
    {MONS_ICE_STATUE, "얼음 조각상"},
    {MONS_OBSIDIAN_STATUE, "흑요석 조각상"},
    {MONS_ORANGE_STATUE, "주황색 수정 조각상"},
    {MONS_STATUE, "조각상"},
    {MONS_TRAINING_DUMMY, "훈련용 허수아비"},
    {MONS_PILLAR_OF_SALT, "소금 기둥"},
    {MONS_BLOCK_OF_ICE, "얼음 덩어리"},
    {MONS_DIAMOND_OBELISK, "다이아몬드 방첨탑"},
    {MONS_LIGHTNING_SPIRE, "번개 첨탑"},
    {MONS_GARGOYLE, "가고일"},
    {MONS_WAR_GARGOYLE, "전쟁 가고일"},
    {MONS_MOLTEN_GARGOYLE, "녹아내린 가고일"},
    {MONS_PANDEMONIUM_LORD, "판데모니움 군주"},
    {MONS_BALL_LIGHTNING, "번개 구체"},
    {MONS_BALLISTOMYCETE_SPORE, "폭발성 포자"},
    {MONS_LOST_SOUL, "길잃은 영혼"},
    {MONS_LURKING_HORROR, "잠복한 공포"},
    {MONS_ORB_OF_FIRE, "화염의 보주"},
    {MONS_ORB_OF_DESTRUCTION, "파괴의 보주"},
    {MONS_FULMINANT_PRISM, "폭발성 프리즘"},
    {MONS_WRETCHED_STAR, "뒤틀린 별"},
    {MONS_BATTLESPHERE, "전투구체"},
    {MONS_DEATH_COB, "죽음의 옥수수"},
    {MONS_MENNAS, "메나스"},
    {MONS_NESSOS, "네소스"},
    {MONS_CHUCK, "척"},
    {MONS_POLYPHEMUS, "폴리페무스"},
    {MONS_ANTAEUS, "안타이오스"},
    {MONS_TIAMAT, "티아마트"},
    {MONS_BAI_SUZHEN, "백소정"},
    {MONS_XTAHUA, "싸후아"},
    {MONS_LERNAEAN_HYDRA, "레르나의 히드라"},
    {MONS_SERPENT_OF_HELL, "지옥의 고룡"},
    {MONS_SERPENT_OF_HELL_COCYTUS, "지옥의 고룡"},
    {MONS_SERPENT_OF_HELL_DIS, "지옥의 고룡"},
    {MONS_SERPENT_OF_HELL_TARTARUS, "지옥의 고룡"},
    {MONS_BAI_SUZHEN_DRAGON, "백소정"},
    {MONS_DUVESSA, "듀베사"},
    {MONS_DOWAN, "도완"},
    {MONS_FANNAR, "판나르"},
    {MONS_PRINCE_RIBBIT, "개굴 왕자"},
    {MONS_IJYB, "이지브"},
    {MONS_ROBIN, "로빈"},
    {MONS_GRUM, "그룸"},
    {MONS_CRAZY_YIUF, "미치광이 이우프"},
    {MONS_JORGRUN, "요르그룬"},
    {MONS_NATASHA, "나타샤"},
    {MONS_ARACHNE, "아라크네"},
    {MONS_ASTERION, "아스테리온"},
    {MONS_AGNES, "아그네스"},
    {MONS_THE_ENCHANTRESS, "인챈트리스"},
    {MONS_ROYAL_JELLY, "로얄 젤리"},
    {MONS_DISSOLUTION, "용해자"},
    {MONS_SONJA, "소냐"},
    {MONS_PIKEL, "피켈"},
    {MONS_BORIS, "보리스"},
    {MONS_MENKAURE, "멘카우레"},
    {MONS_KHUFU, "쿠푸"},
    {MONS_ILSUIW, "일스이우"},
    {MONS_VASHNIA, "바쉬니아"},
    {MONS_EROLCHA, "에롤차"},
    {MONS_BLORK_THE_ORC, "오크 블로크"},
    {MONS_URUG, "우르그"},
    {MONS_NERGALLE, "네르갈"},
    {MONS_SAINT_ROKA, "성자 로카"},
    {MONS_SOJOBO, "소조보"},
    {MONS_AZRAEL, "아즈라엘"},
    {MONS_MARA, "마라"},
    {MONS_AIZUL, "아이줄"},
    {MONS_SNORG, "스노그"},
    {MONS_PURGY, "퍼기"},
    {MONS_MOON_TROLL, "달빛 트롤"},
    {MONS_JORY, "조리"},
    {MONS_GASTRONOK, "가스트로녹"},
    {MONS_NELLIE, "넬리"},
    {MONS_MURRAY, "머레이"},
    {MONS_IGNACIO, "이그나시오"},
    {MONS_GRINDER, "그라인더"},
    {MONS_ROXANNE, "록산느"},
    {MONS_TERENCE, "테렌스"},
    {MONS_JESSICA, "제시카"},
    {MONS_SIGMUND, "시그문드"},
    {MONS_EDMUND, "에드문드"},
    {MONS_PSYCHE, "프시케"},
    {MONS_JOSEPH, "조셉"},
    {MONS_ERICA, "에리카"},
    {MONS_JOSEPHINE, "조세핀"},
    {MONS_HAROLD, "해롤드"},
    {MONS_LOUISE, "루이즈"},
    {MONS_FRANCES, "프랜시스"},
    {MONS_RUPERT, "루퍼트"},
    {MONS_KIRKE, "키르케"},
    {MONS_FREDERICK, "프레데릭"},
    {MONS_MARGERY, "마저리"},
    {MONS_EUSTACHIO, "유스타키오"},
    {MONS_MAURICE, "모리스"},
    {MONS_NIKOLA, "니콜라"},
    {MONS_MNOLEG, "므놀렉"},
    {MONS_LOM_LOBON, "롬 로본"},
    {MONS_CEREBOV, "세레보브"},
    {MONS_GLOORX_VLOQ, "글룩스 블로크"},
    {MONS_GERYON, "게리욘"},
    {MONS_DISPATER, "디스페이터"},
    {MONS_ASMODEUS, "아스모데우스"},
    {MONS_ERESHKIGAL, "에레쉬키갈"},
    {MONS_TEST_SPAWNER, "테스트용 생성기"},
    {MONS_SENSED, "감지된 적"},
    {MONS_SENSED_FRIENDLY, "감지된 아군"},
    {MONS_SENSED_TRIVIAL, "감지된 손쉬운 적"},
    {MONS_SENSED_EASY, "감지된 약한 적"},
    {MONS_SENSED_TOUGH, "감지된 까다로운 적"},
    {MONS_SENSED_NASTY, "감지된 어려운 적"},
};
